# Generated by Django 5.0.3 on 2024-05-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metuFresh', '0002_customer_password_product_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderdetail',
            table='Order_Detail',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
    ]
