# Generated by Django 5.0.3 on 2024-05-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metuFresh', '0003_alter_category_table_alter_customer_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metuFresh.customer')),
            ],
            options={
                'db_table': 'Log_In',
            },
        ),
    ]
