# Generated by Django 5.0.3 on 2024-05-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metuFresh', '0004_log_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_in',
            old_name='user_id',
            new_name='user',
        ),
    ]
