# Generated by Django 4.2.13 on 2024-05-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metuFresh', '0005_rename_user_id_log_in_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log_In',
        ),
    ]
