# Generated by Django 4.2.13 on 2024-05-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metuFresh', '0006_delete_log_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default=5523532, max_length=20),
            preserve_default=False,
        ),
    ]
